#' @include utils.R
#' @include setup.R
#' @include Class-arg-Documentation.R
#' @include Class-data-Documentation.R
#' @include Class-Documentation-Default-Value.R
#' @include Class-Documentation-Keyword.R
#' @include Class-Documentation.R
#' @include Class-example.R
#' @include Class-FormattedText.R
#' @include Class-function-Documentation.R
#' @include Class-option-Documentation.R
#' @include Class-Rd.R
#' @include Class-S4-Documentation.R
#' @include Class-Shared-Documenation.R
#' @include Class-usage.R
#' @include Class-Vector.R
