#' @include Conversions.R
#' @include Classes.R
#' @include utils.R
#' @include setup.R
#' @include Fun-accessors-function.R
#' @include Fun-accessors-option.R
#' @include Fun-accessors.R
#' @include Fun-check_documented.R
#' @include Fun-default.R
#' @include Fun-document.R
#' @include Fun-documentation-S4.R
#' @include Fun-documentation-Shared.R
#' @include Fun-documentation.R
#' @include Fun-extract_documentation-classGeneratorFunction.R
#' @include Fun-extract_documentation.R
#' @include Fun-extract_tests.R
#' @include Fun-format.R
#' @include Fun-toRd-arg.R
#' @include Fun-toRd-Documentation.R
#' @include Fun-toRd-example.R
#' @include Fun-toRd-function.R
#' @include Fun-toRd-option.R
#' @include Fun-toRd-shiny.R
#' @include Fun-toRd-usage.R
#' @include Fun-toRd.R
#' @include Fun-write_documentation.R
